let font;
let points;
let t = 0; // time for noise

async function setup() {
  createCanvas(windowWidth, windowHeight);

  font = await loadFont('assets/Junicode.ttf');
  textSize(300)
  textAlign(CENTER,CENTER)
  points = font.textToPoints('não',width/2,height/2,{
    sampleFactor:0.20,
    simplifyThreshold:0
  })
  console.log(points)

//   noLoop()
}

// function draw() {
//   background(220);
 
//   for(let i=0; i<points.length;i++){
//     let p = points[i]
    
//     point(p.x, p.y)

//     // point(points[i].x,points[i].y) 
//   }
 
// }

function draw() {
  background(220);

  for (let i = 0; i < points.length; i++) {
    let p = points[i];

    let offsetX = map(noise(t + i * 0.05), 0, 1, -10, 10); 

    /**
     * noise returns a value between 0 and 1 that changes smoothly. 
     *  t is time and changes at every frame
     *  i*0.05 if we dont use this, every point will get the exact same value and the multiplication by 0.05 is to make the seed smaller diferences
     *  map(value,0,1,-5,5), we have these values generated by noise, they are between 0 and 1 and are produced with small gaps between them, and we remap to -5 and 5
     */

    point(p.x + offsetX, p.y + offsetX);
  }

  t += 0.01;
}


/** 
 * ANGLE MEANS: we can think of it like THE DIRECTION OF THE CURVE AT THAT POINT, THE TANGENT VECTOR OF THE PATH
 * ALPHA VALUES: HOW MUCH THE PATH IS TURNING AT THAT POINT, small alpha straight, large alpha strong curve, +/- direction
 */


/**
 * 
 * this is a way to understand ANGLE
 */
// function draw() {
//   background(220);

//   for (let p of points) {
//     let deg = degrees(p.angle);
//     let hue = (deg + 360) % 360;

//     push();
//     translate(p.x, p.y);
//     rotate(p.angle);

//     // point itself
//     noStroke();
//     fill(0);
//     circle(0, 0, 5);

//     // direction line
//     stroke(hue, 90, 90);
//     strokeWeight(2);
//     line(0, 0, 24, 0);

//     // arrow head
//     line(24, 0, 18, -5);
//     line(24, 0, 18, 5);

//     pop();
//   }
// }


